services:
  expedientes-app:
    build: .
    container_name: expedientes-app
    restart: unless-stopped
    ports:
      - "8501:8501"  # Puerto est√°ndar de Streamlit
    volumes:
      - .:/app  # Montar la carpeta actual para desarrollo en vivo
    environment:
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ENABLE_CORS=false
      - STREAMLIT_SERVER_ENABLE_XSRF_PROTECTION=false
    command: streamlit run /app/app.py
